global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'taxi-service'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'   # The HTTP resource path on which to fetch metrics from targets.
    static_configs:                        # A static_config allows specifying a list of targets and a common label set for them
      - targets: ['host.docker.internal:8080']